FROM alpine-java:base
MAINTAINER ttstudios.eu
RUN apk --no-cache add netcat-openbsd && apk add dos2unix && apk add curl
COPY files/employee-service.jar /opt/spring-cloud/lib/
COPY files/employee-service-entrypoint.sh /opt/spring-cloud/bin/

RUN dos2unix /opt/spring-cloud/bin/employee-service-entrypoint.sh && apk del dos2unix && rm -rf /var/lib/apt/lists/*

RUN chmod 755 /opt/spring-cloud/bin/employee-service-entrypoint.sh
